// AI solutions: the solution categories the enterprise AI market is buying
// today (2026), as Linkfields delivers them. `demos` links each solution to the
// live LFI AI demos that show it working (ids from demos.js); `stack` names the
// building blocks used. `mark` is its element-style symbol and accent colour.
//
// Note for reviewers: these are presented as Linkfields AI solutions at the
// business's request. Confirm wording with the solutions team before launch.

const s = (id, name, tagline, summary, useCases, stack, demos, mark) => ({
  id,
  name,
  tagline,
  summary,
  useCases,
  stack,
  demos,
  mark,
});

export const aiSolutions = [
  s('generative-ai', 'Generative AI and Copilots', 'Copilots that draft, summarise and analyse inside your systems',
    'Secure, governed generative AI built into the tools your teams already use, from drafting reports and proposals to summarising long documents and analysing data in plain language.',
    ['Enterprise copilots', 'Report and content generation', 'Data analysis in natural language'],
    ['Foundation models (Claude, GPT, Llama)', 'Private deployment', 'Usage and cost governance'],
    ['textiq', 'finsight', 'edupilot', 'digital-growth-intelligence'],
    { code: 'Gn', accent: '#ff9900' }),
  s('agentic-ai', 'Agentic AI and AI Agents', 'Agents that plan and complete multi-step work',
    'AI agents that reason over a goal, call approved tools and APIs, and complete multi-step business tasks, with human approval gates, guardrails and full audit trails.',
    ['Back-office process agents', 'IT and service-desk agents', 'Research and analyst agents'],
    ['Model Context Protocol (MCP) tools', 'Multi-agent orchestration', 'Approval and audit controls'],
    ['vajrax'],
    { code: 'Ag', accent: '#ffb547' }),
  s('enterprise-rag', 'Enterprise RAG and Knowledge Search', 'Answers grounded in your own documents, with sources',
    'Retrieval-augmented generation over policies, manuals, contracts and tickets: permission-aware search that answers questions and cites the exact sources it used.',
    ['Policy and procedure assistants', 'Knowledge-base search', 'Contract and document Q&A'],
    ['Vector and hybrid search', 'Access-control trimming', 'Citation and evaluation'],
    ['rag-chatbot', 'rag-mobile'],
    { code: 'Rg', accent: '#539fe5' }),
  s('conversational-ai', 'Conversational and Voice AI', 'Natural assistants on web, mobile, kiosk and phone',
    'Customer and employee assistants that understand intent, hold real conversations by text or voice and hand over to people when needed.',
    ['Customer service assistants', 'Self-service kiosks', 'Contact-centre voice agents'],
    ['Speech-to-text and text-to-speech', 'Real-time dialogue', 'Channel and telephony integration'],
    ['rag-chatbot', 'unmanned-kiosk', 'edupilot'],
    { code: 'Cv', accent: '#2bd4c4' }),
  s('document-intelligence', 'Intelligent Document Processing', 'From forms, claims and CVs to structured data',
    'Extraction, classification and validation of data from documents of every kind, using OCR, layout understanding and language models for straight-through processing.',
    ['Claims and onboarding documents', 'Invoice and contract extraction', 'CV screening and matching'],
    ['OCR and layout analysis', 'LLM field extraction', 'Human-in-the-loop review'],
    ['textiq', 'vajrax', 'resume-summarizer', 'jd-cv-comparison'],
    { code: 'Dp', accent: '#ffd27a' }),
  s('computer-vision', 'Computer Vision and Multimodal AI', 'Models that see, read and describe',
    'Image and video understanding combined with language: inspection, movement analysis and visual search, reported in plain language.',
    ['Visual quality inspection', 'Pose and movement analysis', 'Signature and identity checks'],
    ['Vision transformers', 'Multimodal models', 'Edge deployment'],
    ['golf-analyzer', 'signature-fraud'],
    { code: 'Vi', accent: '#ff6a3d' }),
  s('predictive-analytics', 'Predictive Analytics and Forecasting', 'Forecast demand, churn and lifetime value',
    'Machine-learning models that predict what happens next: customer churn, lifetime value, demand, lapse and next best offer, monitored and retrained in production.',
    ['Churn and retention', 'Demand and inventory forecasting', 'Customer lifetime value'],
    ['Gradient boosting and deep learning', 'Feature stores', 'Drift monitoring'],
    ['banking-analytics', 'telecom-analytics', 'demand-forecasting', 'clv-banking-telecom', 'lapse-prediction'],
    { code: 'Pa', accent: '#37c871' }),
  s('fraud-risk', 'Fraud, Risk and Anomaly Detection', 'Detect what does not belong, in real time',
    'Detection of fraudulent claims, transactions and network behaviour, plus credit and insurance risk scoring that explains its decisions.',
    ['Claims and transaction fraud', 'Credit risk scoring', 'Network anomaly detection'],
    ['Anomaly detection', 'Graph analytics', 'Explainable AI'],
    ['insurance-claims-fraud', 'banking-claims-fraud', 'network-fraud', 'credit-risk', 'risk-score'],
    { code: 'Fr', accent: '#ff4d6d' }),
  s('customer-intelligence', 'Customer Intelligence and Personalisation', 'The next best action for every customer',
    'A 360-degree view of every customer, sentiment analysis and next-best-offer engines that personalise every interaction across channels.',
    ['Next best offer', 'Customer 360 and segmentation', 'Sentiment analysis'],
    ['Recommendation engines', 'Customer data platforms', 'Real-time scoring'],
    ['customer-360', 'nbo-revenue', 'nbo-data-engine', 'engage360', 'banking-sentiment'],
    { code: 'Ci', accent: '#c58bff' }),
  s('intelligent-automation', 'Intelligent Automation', 'RPA bots that understand language and exceptions',
    'Robotic process automation extended with language and vision models, so bots can read unstructured inputs, triage exceptions and keep people in the loop.',
    ['Finance and HR automation', 'Exception triage', 'Email and request handling'],
    ['UiPath and Automation Anywhere', 'LLM-assisted bots', 'Process mining'],
    ['vajrax', 'textiq'],
    { code: 'Ia', accent: '#7fb3ff' }),
  s('industrial-ai', 'Digital Twins and Industrial AI', 'Predict failures before they happen',
    'Digital twins, predictive maintenance and KPI monitoring for plants, networks and fleets, combining IoT data with machine learning.',
    ['Predictive maintenance', 'Digital twins', 'Smart KPI monitoring'],
    ['IoT data pipelines', 'Time-series models', 'Simulation'],
    ['equipment-failure', 'digital-twin', 'smart-kpi'],
    { code: 'Dt', accent: '#c9a36b' }),
  s('ai-governance', 'AI Governance, Security and Responsible AI', 'Trustworthy AI, by design',
    'Policies, controls and monitoring for safe, compliant AI: risk assessment, prompt-injection defence, model and data governance, aligned to ISO/IEC 42001 and the EU AI Act.',
    ['AI risk assessment', 'Guardrails and red-teaming', 'Model and data governance'],
    ['ISO/IEC 42001', 'Guardrail frameworks', 'AI observability'],
    ['cybersecurity-lms'],
    { code: 'Gv', accent: '#9aa7b8' }),
];

export const aiSolutionById = Object.fromEntries(aiSolutions.map((x) => [x.id, x]));
